apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount
    app.kubernetes.io/part-of: devfile-sample-go-basic-zj-app
  name: managed-serviceaccount
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: managed-serviceaccount
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: managed-serviceaccount
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8077
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
