apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount
    app.kubernetes.io/part-of: devfile-sample-go-basic-zj-app
  name: managed-serviceaccount
spec:
  ports:
  - port: 8077
    targetPort: 8077
  selector:
    app.kubernetes.io/instance: managed-serviceaccount
status:
  loadBalancer: {}
