apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-zj-c1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jiazhu-tenant/devfile-sample-go-basic-zj-app/devfile-sample-go-basic-zj-c1@sha256:8445635827f55a6c89e8539c306c21dfc6a101d323b0df92ad2ffd2b062ff346
        name: my-go
        resources: {}
status: {}
