apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-zj-c1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-zj-c1
    app.kubernetes.io/part-of: devfile-sample-go-basic-zj-app
  name: devfile-sample-go-basic-zj-c1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-zj-c1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-zj-c1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jiazhu-tenant/devfile-sample-go-basic-zj-app/devfile-sample-go-basic-zj-c1@sha256:8445635827f55a6c89e8539c306c21dfc6a101d323b0df92ad2ffd2b062ff346
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
